projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:8000/graphql
  db:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      endpoints:
        default: 'http://localhost:4477/divstff/dev'